services:
  - type: web
    name: lab2-backend
    env: python
    plan: free
    repo: https://github.com/GentleBear2612/lab2_25099433g
    branch: vercel-deploy
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT src.main:app
